from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from tests.dependency_lock_helpers import (
    LOCK_PATHS,
    LOCK_SCRIPT,
    ROOT,
    copy_lock_inputs,
    load_lock_module,
    requirement_blocks,
    run_check,
)


@pytest.mark.parametrize("path", LOCK_PATHS)
def test_lock_files_pin_and_hash_every_requirement(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "autogenerated" in text.lower()
    blocks = requirement_blocks(text)
    assert blocks
    assert all("==" in block for block in blocks)
    assert all("--hash=sha256:" in block for block in blocks)


def test_detector_lock_preserves_cpu_package_index() -> None:
    text = (ROOT / "requirements-detector.lock").read_text(encoding="utf-8")
    assert "--extra-index-url https://download.pytorch.org/whl/cpu" in text
    for package in ("torch==2.7.1+cpu", "torchvision==0.22.1+cpu", "ultralytics==8.4.60"):
        assert package in text


def test_build_toolchain_is_fully_exact_pinned() -> None:
    lines = (ROOT / "requirements-build.txt").read_text(encoding="utf-8").splitlines()
    assert lines
    assert "pip-tools==7.5.0" in lines
    assert "pip==24.0" in lines
    assert all("==" in line and not line.startswith((" ", "#", "--")) for line in lines)


def test_build_tool_lock_is_hash_pinned_to_explicit_pypi() -> None:
    path = ROOT / "requirements-build.lock"
    text = path.read_text(encoding="utf-8")
    assert text.splitlines()[3] == "--index-url https://pypi.org/simple"
    blocks = requirement_blocks(text)
    assert blocks
    assert all("==" in block for block in blocks)
    assert all("--hash=sha256:" in block for block in blocks)


def test_lock_generator_modules_stay_below_decomposition_caps() -> None:
    assert len(LOCK_SCRIPT.read_text(encoding="utf-8").splitlines()) <= 400
    support = ROOT / "scripts" / "dependency_lock_validation.py"
    assert len(support.read_text(encoding="utf-8").splitlines()) <= 350


def test_lock_check_reports_current_manifests_without_installed_pip_tools() -> None:
    completed = run_check(ROOT)
    assert completed.returncode == 0, completed.stderr
    assert "dependency locks are current" in completed.stdout.lower()


def test_lock_check_does_not_create_validation_bytecode(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)

    completed = run_check(root)

    assert completed.returncode == 0, completed.stderr
    assert not (root / "scripts" / "__pycache__").exists()


@pytest.mark.parametrize(
    ("relative_path", "expected_message"),
    [
        ("requirements-build.lock", "missing"),
        ("requirements-runtime.lock", "missing"),
        ("requirements-detector.lock", "missing"),
    ],
)
def test_lock_check_reports_missing_lock_without_creating_it(
    tmp_path: Path,
    relative_path: str,
    expected_message: str,
) -> None:
    root = copy_lock_inputs(tmp_path)
    lock_path = root / relative_path
    lock_path.unlink()

    completed = run_check(root)

    assert completed.returncode == 1
    assert expected_message in completed.stderr.lower()
    assert relative_path in completed.stderr
    assert not lock_path.exists()


def test_lock_check_reports_stale_locks_without_overwriting_them(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    source = root / "requirements.txt"
    source.write_text(source.read_text(encoding="utf-8") + "sniffio>=1\n", encoding="utf-8")
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )
    before = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }

    completed = run_check(root)

    assert completed.returncode == 1
    assert "stale" in completed.stderr.lower()
    assert "requirements-runtime.lock" in completed.stderr
    assert "requirements-detector.lock" in completed.stderr
    after = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }
    assert after == before


def test_lock_check_rejects_header_only_locks(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    digest = load_lock_module().compute_source_digest(root)
    header = f"# This file is autogenerated.\n# source-sha256: {digest}\n"
    for path in (root / "requirements-runtime.lock", root / "requirements-detector.lock"):
        path.write_text(header, encoding="utf-8")

    completed = run_check(root)

    assert completed.returncode == 1
    assert "invalid dependency lock" in completed.stderr.lower()
    assert "requirements-runtime.lock" in completed.stderr
    assert "requirements-detector.lock" in completed.stderr


def test_lock_check_rejects_pyproject_dependency_drift(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )

    completed = run_check(root)

    assert completed.returncode == 1
    assert "dependency input mismatch" in completed.stderr.lower()
    assert "requirements.txt" in completed.stderr


def test_source_digest_ignores_unrelated_project_metadata(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'description = "Local parking spot monitor for UniFi Protect RTSP streams."',
            'description = "Changed non-dependency metadata."',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) == original


def test_source_digest_changes_with_project_dependencies(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) != original


def test_source_digest_ignores_dev_only_dependencies(tmp_path: Path) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "pytest>=8",',
            '    "pytest>=8",\n    "coverage>=7",',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) == original


def test_detector_index_normalization_rejects_unexpected_compiler_output() -> None:
    module = load_lock_module()

    with pytest.raises(RuntimeError, match="index directives"):
        module.normalize_detector_indexes("torch==2.7.1+cpu \\\n")


def test_detector_index_normalization_restores_portable_index_order() -> None:
    module = load_lock_module()
    compiled = (
        "--index-url https://download.pytorch.org/whl/cpu\n"
        "--extra-index-url https://pypi.org/simple\n\n"
        "torch==2.7.1+cpu \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )

    normalized = module.normalize_detector_indexes(compiled)

    assert normalized.startswith(
        "--index-url https://pypi.org/simple\n"
        "--extra-index-url https://download.pytorch.org/whl/cpu\n\n"
    )
    assert "torch==2.7.1+cpu" in normalized


def test_input_manifests_keep_broad_runtime_bounds() -> None:
    assert (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines() == [
        "httpx>=0.27",
        "Pillow>=10",
        "pydantic>=2",
        "PyYAML>=6",
    ]
