from __future__ import annotations

import hashlib
import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import sys

import pytest


ROOT = Path(__file__).resolve().parents[1]
LOCK_SCRIPT = ROOT / "scripts" / "lock_dependencies.py"
LOCK_PATHS = (
    ROOT / "requirements-runtime.lock",
    ROOT / "requirements-detector.lock",
)


def _run_check(root: Path) -> subprocess.CompletedProcess[str]:
    environment = {
        **os.environ,
        "PIP_NO_INDEX": "1",
        "PIP_DISABLE_PIP_VERSION_CHECK": "1",
        "PYTHONNOUSERSITE": "1",
    }
    return subprocess.run(
        [sys.executable, str(root / "scripts" / "lock_dependencies.py"), "--check"],
        cwd=root,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )


def _copy_lock_inputs(tmp_path: Path) -> Path:
    root = tmp_path / "repository"
    (root / "scripts").mkdir(parents=True)
    for relative in (
        "requirements.txt",
        "requirements-detector.txt",
        "pyproject.toml",
        "requirements-runtime.lock",
        "requirements-detector.lock",
        "scripts/lock_dependencies.py",
    ):
        source = ROOT / relative
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return root


def _requirement_blocks(text: str) -> list[str]:
    lines = text.splitlines()
    blocks: list[str] = []
    current: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")) and stripped.startswith("--"):
            continue
        if not line.startswith((" ", "\t")):
            if current:
                blocks.append("\n".join(current))
            current = [stripped]
        elif current:
            current.append(stripped)
    if current:
        blocks.append("\n".join(current))
    return blocks


@pytest.mark.parametrize("path", LOCK_PATHS)
def test_lock_files_pin_and_hash_every_requirement(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "autogenerated" in text.lower()
    blocks = _requirement_blocks(text)
    assert blocks
    assert all("==" in block for block in blocks)
    assert all("--hash=sha256:" in block for block in blocks)


def test_detector_lock_preserves_cpu_package_index() -> None:
    text = (ROOT / "requirements-detector.lock").read_text(encoding="utf-8")
    assert "--extra-index-url https://download.pytorch.org/whl/cpu" in text
    for package in ("torch==2.7.1+cpu", "torchvision==0.22.1+cpu", "ultralytics==8.4.60"):
        assert package in text


def test_build_tool_is_exactly_pinned() -> None:
    assert (ROOT / "requirements-build.txt").read_text(encoding="utf-8") == (
        "pip-tools==7.5.0\n"
    )


def test_lock_check_reports_current_manifests_without_installed_pip_tools() -> None:
    completed = _run_check(ROOT)
    assert completed.returncode == 0, completed.stderr
    assert "dependency locks are current" in completed.stdout.lower()


@pytest.mark.parametrize(
    ("relative_path", "expected_message"),
    [
        ("requirements-runtime.lock", "missing"),
        ("requirements-detector.lock", "missing"),
    ],
)
def test_lock_check_reports_missing_lock_without_creating_it(
    tmp_path: Path,
    relative_path: str,
    expected_message: str,
) -> None:
    root = _copy_lock_inputs(tmp_path)
    lock_path = root / relative_path
    lock_path.unlink()

    completed = _run_check(root)

    assert completed.returncode == 1
    assert expected_message in completed.stderr.lower()
    assert relative_path in completed.stderr
    assert not lock_path.exists()


def test_lock_check_reports_stale_locks_without_overwriting_them(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    source = root / "requirements.txt"
    source.write_text(source.read_text(encoding="utf-8") + "sniffio>=1\n", encoding="utf-8")
    before = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }

    completed = _run_check(root)

    assert completed.returncode == 1
    assert "stale" in completed.stderr.lower()
    assert "requirements-runtime.lock" in completed.stderr
    assert "requirements-detector.lock" in completed.stderr
    after = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }
    assert after == before


def _load_lock_module():
    spec = importlib.util.spec_from_file_location("lock_dependencies", LOCK_SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_source_digest_ignores_unrelated_project_metadata(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'description = "Local parking spot monitor for UniFi Protect RTSP streams."',
            'description = "Changed non-dependency metadata."',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) == original


def test_source_digest_changes_with_project_dependencies(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) != original


def test_detector_index_normalization_rejects_unexpected_compiler_output() -> None:
    module = _load_lock_module()

    with pytest.raises(RuntimeError, match="index directives"):
        module.normalize_detector_indexes("torch==2.7.1+cpu \\\n")


def test_detector_index_normalization_restores_portable_index_order() -> None:
    module = _load_lock_module()
    compiled = (
        "--index-url https://download.pytorch.org/whl/cpu\n"
        "--extra-index-url https://pypi.org/simple\n\n"
        "torch==2.7.1+cpu \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )

    normalized = module.normalize_detector_indexes(compiled)

    assert normalized.startswith(
        "--extra-index-url https://download.pytorch.org/whl/cpu\n\n"
    )
    assert "--index-url" not in normalized
    assert "https://pypi.org/simple" not in normalized
    assert "torch==2.7.1+cpu" in normalized


def test_input_manifests_keep_broad_runtime_bounds() -> None:
    assert (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines() == [
        "httpx>=0.27",
        "Pillow>=10",
        "pydantic>=2",
        "PyYAML>=6",
    ]
