from __future__ import annotations

import hashlib
import importlib.util
import os
from pathlib import Path
import shutil
import subprocess
import sys
from types import SimpleNamespace

import pytest


ROOT = Path(__file__).resolve().parents[1]
LOCK_SCRIPT = ROOT / "scripts" / "lock_dependencies.py"
LOCK_PATHS = (
    ROOT / "requirements-runtime.lock",
    ROOT / "requirements-detector.lock",
)


def _run_check(root: Path) -> subprocess.CompletedProcess[str]:
    environment = {
        **os.environ,
        "PIP_NO_INDEX": "1",
        "PIP_DISABLE_PIP_VERSION_CHECK": "1",
        "PYTHONNOUSERSITE": "1",
    }
    return subprocess.run(
        [sys.executable, str(root / "scripts" / "lock_dependencies.py"), "--check"],
        cwd=root,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )


def _copy_lock_inputs(tmp_path: Path) -> Path:
    root = tmp_path / "repository"
    (root / "scripts").mkdir(parents=True)
    for relative in (
        "requirements.txt",
        "requirements-detector.txt",
        "requirements-build.txt",
        "pyproject.toml",
        "requirements-runtime.lock",
        "requirements-detector.lock",
        "scripts/lock_dependencies.py",
    ):
        source = ROOT / relative
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return root


def _requirement_blocks(text: str) -> list[str]:
    lines = text.splitlines()
    blocks: list[str] = []
    current: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not line.startswith((" ", "\t")) and stripped.startswith("--"):
            continue
        if not line.startswith((" ", "\t")):
            if current:
                blocks.append("\n".join(current))
            current = [stripped]
        elif current:
            current.append(stripped)
    if current:
        blocks.append("\n".join(current))
    return blocks


@pytest.mark.parametrize("path", LOCK_PATHS)
def test_lock_files_pin_and_hash_every_requirement(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "autogenerated" in text.lower()
    blocks = _requirement_blocks(text)
    assert blocks
    assert all("==" in block for block in blocks)
    assert all("--hash=sha256:" in block for block in blocks)


def test_detector_lock_preserves_cpu_package_index() -> None:
    text = (ROOT / "requirements-detector.lock").read_text(encoding="utf-8")
    assert "--extra-index-url https://download.pytorch.org/whl/cpu" in text
    for package in ("torch==2.7.1+cpu", "torchvision==0.22.1+cpu", "ultralytics==8.4.60"):
        assert package in text


def test_build_toolchain_is_fully_exact_pinned() -> None:
    lines = (ROOT / "requirements-build.txt").read_text(encoding="utf-8").splitlines()
    assert lines
    assert "pip-tools==7.5.0" in lines
    assert "pip==24.0" in lines
    assert all("==" in line and not line.startswith((" ", "#", "--")) for line in lines)


def test_lock_check_reports_current_manifests_without_installed_pip_tools() -> None:
    completed = _run_check(ROOT)
    assert completed.returncode == 0, completed.stderr
    assert "dependency locks are current" in completed.stdout.lower()


@pytest.mark.parametrize(
    ("relative_path", "expected_message"),
    [
        ("requirements-runtime.lock", "missing"),
        ("requirements-detector.lock", "missing"),
    ],
)
def test_lock_check_reports_missing_lock_without_creating_it(
    tmp_path: Path,
    relative_path: str,
    expected_message: str,
) -> None:
    root = _copy_lock_inputs(tmp_path)
    lock_path = root / relative_path
    lock_path.unlink()

    completed = _run_check(root)

    assert completed.returncode == 1
    assert expected_message in completed.stderr.lower()
    assert relative_path in completed.stderr
    assert not lock_path.exists()


def test_lock_check_reports_stale_locks_without_overwriting_them(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    source = root / "requirements.txt"
    source.write_text(source.read_text(encoding="utf-8") + "sniffio>=1\n", encoding="utf-8")
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )
    before = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }

    completed = _run_check(root)

    assert completed.returncode == 1
    assert "stale" in completed.stderr.lower()
    assert "requirements-runtime.lock" in completed.stderr
    assert "requirements-detector.lock" in completed.stderr
    after = {
        path.name: (path.read_bytes(), hashlib.sha256(path.read_bytes()).hexdigest())
        for path in (
            root / "requirements-runtime.lock",
            root / "requirements-detector.lock",
        )
    }
    assert after == before


def test_lock_check_rejects_header_only_locks(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    digest = _load_lock_module().compute_source_digest(root)
    header = f"# This file is autogenerated.\n# source-sha256: {digest}\n"
    for path in (root / "requirements-runtime.lock", root / "requirements-detector.lock"):
        path.write_text(header, encoding="utf-8")

    completed = _run_check(root)

    assert completed.returncode == 1
    assert "invalid dependency lock" in completed.stderr.lower()
    assert "requirements-runtime.lock" in completed.stderr
    assert "requirements-detector.lock" in completed.stderr


def test_lock_check_rejects_pyproject_dependency_drift(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )

    completed = _run_check(root)

    assert completed.returncode == 1
    assert "dependency input mismatch" in completed.stderr.lower()
    assert "requirements.txt" in completed.stderr


def _load_lock_module():
    spec = importlib.util.spec_from_file_location("lock_dependencies", LOCK_SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_source_digest_ignores_unrelated_project_metadata(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'description = "Local parking spot monitor for UniFi Protect RTSP streams."',
            'description = "Changed non-dependency metadata."',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) == original


def test_source_digest_changes_with_project_dependencies(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "PyYAML>=6",',
            '    "PyYAML>=6",\n    "sniffio>=1",',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) != original


def test_source_digest_ignores_dev_only_dependencies(tmp_path: Path) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    original = module.compute_source_digest(root)
    pyproject = root / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "pytest>=8",',
            '    "pytest>=8",\n    "coverage>=7",',
        ),
        encoding="utf-8",
    )

    assert module.compute_source_digest(root) == original


def test_detector_index_normalization_rejects_unexpected_compiler_output() -> None:
    module = _load_lock_module()

    with pytest.raises(RuntimeError, match="index directives"):
        module.normalize_detector_indexes("torch==2.7.1+cpu \\\n")


def test_detector_index_normalization_restores_portable_index_order() -> None:
    module = _load_lock_module()
    compiled = (
        "--index-url https://download.pytorch.org/whl/cpu\n"
        "--extra-index-url https://pypi.org/simple\n\n"
        "torch==2.7.1+cpu \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )

    normalized = module.normalize_detector_indexes(compiled)

    assert normalized.startswith(
        "--index-url https://pypi.org/simple\n"
        "--extra-index-url https://download.pytorch.org/whl/cpu\n\n"
    )
    assert "torch==2.7.1+cpu" in normalized


def test_input_manifests_keep_broad_runtime_bounds() -> None:
    assert (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines() == [
        "httpx>=0.27",
        "Pillow>=10",
        "pydantic>=2",
        "PyYAML>=6",
    ]


def _compiled_requirement(name: str, version: str = "1.0") -> str:
    return f"{name}=={version} \\\n    --hash=sha256:{'a' * 64}\n"


def _valid_compiled(source: str) -> str:
    if source == "requirements.txt":
        # pip-tools suppresses its default PyPI directive even when supplied
        # explicitly; the generator must make the reviewed install source explicit.
        directives = ""
        requirements = ("httpx", "pillow", "pydantic", "pyyaml")
    else:
        directives = (
            "--index-url https://download.pytorch.org/whl/cpu\n"
            "--extra-index-url https://pypi.org/simple\n\n"
        )
        requirements = ("torch", "torchvision", "ultralytics")
    return directives + "".join(_compiled_requirement(name) for name in requirements)


def test_generation_sanitizes_indexes_and_publishes_explicit_sources(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    monkeypatch.setattr(module, "_validate_build_tool", lambda _root: None)
    calls: list[tuple[list[str], dict[str, str]]] = []

    def fake_run(command, *, cwd, check, env):
        output = next(
            arg.split("=", 1)[1]
            for arg in command
            if arg.startswith("--output-file=")
        )
        source = command[-1]
        (root / output).write_text(_valid_compiled(source), encoding="utf-8")
        calls.append((command, env))
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(module.subprocess, "run", fake_run)
    monkeypatch.setenv("PIP_INDEX_URL", "https://untrusted.invalid/simple")
    monkeypatch.setenv("PIP_EXTRA_INDEX_URL", "https://also-untrusted.invalid/simple")
    monkeypatch.setenv("PIP_FIND_LINKS", "/untrusted/wheels")
    monkeypatch.setenv("PIP_NO_INDEX", "1")
    monkeypatch.setenv("PIP_TRUSTED_HOST", "untrusted.invalid")

    module.generate_locks(root)

    assert len(calls) == 2
    for command, environment in calls:
        assert command[:4] == [sys.executable, "-P", "-m", "piptools"]
        assert any(
            argument
            in (
                "--index-url=https://pypi.org/simple",
                "--index-url=https://download.pytorch.org/whl/cpu",
            )
            for argument in command
        )
        for name in (
            "PIP_INDEX_URL",
            "PIP_EXTRA_INDEX_URL",
            "PIP_FIND_LINKS",
            "PIP_NO_INDEX",
            "PIP_TRUSTED_HOST",
        ):
            assert name not in environment
        assert environment["PIP_CONFIG_FILE"] == os.devnull
        assert "PYTHONPATH" not in environment
        assert environment["PYTHONSAFEPATH"] == "1"
    assert (
        root.joinpath("requirements-runtime.lock")
        .read_text(encoding="utf-8")
        .splitlines()[3]
        == "--index-url https://pypi.org/simple"
    )
    assert (
        root.joinpath("requirements-detector.lock")
        .read_text(encoding="utf-8")
        .splitlines()[3:5]
        == [
            "--index-url https://pypi.org/simple",
            "--extra-index-url https://download.pytorch.org/whl/cpu",
        ]
    )


@pytest.mark.parametrize(
    "bad_output",
    [
        "httpx==1.0\n",
        (
            "httpx==1.0\n"
            f"    --hash=sha256:{'a' * 64}\n"
        ),
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}\n"
            f"    --hash=sha256:{'b' * 64}\n"
        ),
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64} \\\n"
        ),
        (
            "httpx>=1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}\n"
        ),
        (
            "--index-url https://unexpected.invalid/simple\n\n"
            + _compiled_requirement("httpx")
        ),
    ],
)
def test_malformed_successful_compiler_output_preserves_both_locks_and_cleans_temps(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, bad_output: str
) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    monkeypatch.setattr(module, "_validate_build_tool", lambda _root: None)
    before = {
        name: root.joinpath(name).read_bytes()
        for name in ("requirements-runtime.lock", "requirements-detector.lock")
    }

    def fake_run(command, *, cwd, check, env):
        output = next(
            arg.split("=", 1)[1]
            for arg in command
            if arg.startswith("--output-file=")
        )
        source = command[-1]
        text = bad_output if source == "requirements.txt" else _valid_compiled(source)
        (root / output).write_text(text, encoding="utf-8")
        return SimpleNamespace(returncode=0)

    monkeypatch.setattr(module.subprocess, "run", fake_run)

    with pytest.raises(RuntimeError, match="invalid generated dependency lock"):
        module.generate_locks(root)

    after = {
        name: root.joinpath(name).read_bytes()
        for name in ("requirements-runtime.lock", "requirements-detector.lock")
    }
    assert after == before
    assert list(root.glob(".*.lock.*.tmp")) == []


def test_compiler_failure_preserves_both_locks_and_cleans_temps(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    monkeypatch.setattr(module, "_validate_build_tool", lambda _root: None)
    before = {
        name: root.joinpath(name).read_bytes()
        for name in ("requirements-runtime.lock", "requirements-detector.lock")
    }

    def fake_run(command, *, cwd, check, env):
        output = next(
            arg.split("=", 1)[1]
            for arg in command
            if arg.startswith("--output-file=")
        )
        if command[-1] == "requirements.txt":
            (root / output).write_text(
                _valid_compiled(command[-1]), encoding="utf-8"
            )
            return SimpleNamespace(returncode=0)
        raise subprocess.CalledProcessError(1, command)

    monkeypatch.setattr(module.subprocess, "run", fake_run)

    with pytest.raises(subprocess.CalledProcessError):
        module.generate_locks(root)

    after = {
        name: root.joinpath(name).read_bytes()
        for name in ("requirements-runtime.lock", "requirements-detector.lock")
    }
    assert after == before
    assert list(root.glob(".*.lock.*.tmp")) == []


def test_build_tool_validation_rejects_any_pinned_version_mismatch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    expected = module._required_build_tool_versions(root)
    mismatched = next(iter(expected))

    monkeypatch.setattr(
        module.importlib.metadata,
        "version",
        lambda name: "0.0" if name == mismatched else expected[name],
    )

    with pytest.raises(RuntimeError, match=mismatched):
        module._validate_build_tool(root)


def test_input_requirement_name_handles_supported_compatible_release() -> None:
    module = _load_lock_module()

    assert module._input_requirement_name("Example_Package~=1.2") == "example-package"


def test_input_requirement_rejects_markers_instead_of_misparsing_direct_name() -> None:
    module = _load_lock_module()

    with pytest.raises(RuntimeError, match="unsupported dependency requirement"):
        module._canonical_input_requirement('example>=1; python_version >= "3.12"')


@pytest.mark.parametrize(
    "broken_block",
    [
        "httpx==1.0\n" + f"    --hash=sha256:{'a' * 64}\n",
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}\n"
            f"    --hash=sha256:{'b' * 64}\n"
        ),
        "httpx==1.0 \\\n" + f"    --hash=sha256:{'a' * 64} \\\n",
    ],
)
def test_lock_validation_rejects_broken_continuation_syntax(
    tmp_path: Path, broken_block: str
) -> None:
    root = _copy_lock_inputs(tmp_path)
    module = _load_lock_module()
    digest = module.compute_source_digest(root)
    text = (
        "# This file is autogenerated by scripts/lock_dependencies.py.\n"
        f"# source-sha256: {digest}\n\n"
        "--index-url https://pypi.org/simple\n\n"
        + broken_block
        + _compiled_requirement("pillow")
        + _compiled_requirement("pydantic")
        + _compiled_requirement("pyyaml")
    )

    with pytest.raises(RuntimeError, match="continuation"):
        module._validate_lock_text(
            root,
            "requirements.txt",
            "requirements-runtime.lock",
            text,
            digest,
        )
