from __future__ import annotations

from pathlib import Path
import subprocess
import sys

import pytest

from tests.dependency_lock_helpers import (
    LOCK_SCRIPT,
    ROOT,
    compiled_requirement,
    copy_lock_inputs,
    load_lock_module,
    lock_pin_versions,
)


def test_build_tool_validation_rejects_any_pinned_version_mismatch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    expected = lock_pin_versions(
        (root / "requirements-build.lock").read_text(encoding="utf-8")
    )
    mismatched = next(iter(expected))

    monkeypatch.setattr(
        module.importlib.metadata,
        "version",
        lambda name: "0.0" if name == mismatched else expected[name],
    )

    with pytest.raises(RuntimeError, match=mismatched):
        module._validate_build_tool(root)


def test_input_requirement_name_handles_supported_minimum_release() -> None:
    module = load_lock_module()

    assert module._input_requirement_name("Example_Package>=1.2") == "example-package"


def test_input_requirement_rejects_markers_instead_of_misparsing_direct_name() -> None:
    module = load_lock_module()

    with pytest.raises(RuntimeError, match="unsupported dependency requirement"):
        module._canonical_input_requirement('example>=1; python_version >= "3.12"')


@pytest.mark.parametrize(
    "broken_block",
    [
        "httpx==1.0\n" + f"    --hash=sha256:{'a' * 64}\n",
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}\n"
            f"    --hash=sha256:{'b' * 64}\n"
        ),
        "httpx==1.0 \\\n" + f"    --hash=sha256:{'a' * 64} \\\n",
    ],
)
def test_lock_validation_rejects_broken_continuation_syntax(
    tmp_path: Path, broken_block: str
) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    digest = module.compute_source_digest(root)
    text = (
        "# This file is autogenerated by scripts/lock_dependencies.py.\n"
        f"# source-sha256: {digest}\n\n"
        "--index-url https://pypi.org/simple\n\n"
        + broken_block
        + compiled_requirement("pillow")
        + compiled_requirement("pydantic")
        + compiled_requirement("pyyaml")
    )

    with pytest.raises(RuntimeError, match="continuation"):
        module._validate_lock_text(
            root,
            "requirements.txt",
            "requirements-runtime.lock",
            text,
            digest,
        )


@pytest.mark.parametrize(
    "broken_block",
    [
        "httpx==1.0 \\  \n" + f"    --hash=sha256:{'a' * 64}\n",
        "httpx==1.0\\\n" + f"    --hash=sha256:{'a' * 64}\n",
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}  \\\n"
            f"    --hash=sha256:{'b' * 64}\n"
        ),
        (
            "httpx==1.0 \\\n"
            f"    --hash=sha256:{'a' * 64}\n"
            f"    --hash=sha256:{'b' * 64}\n"
        ),
        "httpx==1.0 \\\n" + f"    --hash=sha256:{'a' * 64}  \n",
    ],
)
def test_lock_validation_rejects_raw_whitespace_and_backslash_corruption(
    tmp_path: Path, broken_block: str
) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    digest = module.compute_source_digest(root)
    text = (
        "# This file is autogenerated by scripts/lock_dependencies.py.\n"
        f"# source-sha256: {digest}\n\n"
        "--index-url https://pypi.org/simple\n\n"
        + broken_block
        + compiled_requirement("pillow", "12.3.0")
        + compiled_requirement("pydantic", "2.13.4")
        + compiled_requirement("pyyaml", "6.0.3")
    )

    with pytest.raises(RuntimeError, match="whitespace|continuation"):
        module._validate_lock_text(
            root,
            "requirements.txt",
            "requirements-runtime.lock",
            text,
            digest,
        )


def test_lock_validation_rejects_direct_pin_outside_input_constraint(
    tmp_path: Path,
) -> None:
    root = copy_lock_inputs(tmp_path)
    module = load_lock_module()
    digest = module.compute_source_digest(root)
    text = (
        "# This file is autogenerated by scripts/lock_dependencies.py.\n"
        f"# source-sha256: {digest}\n\n"
        "--index-url https://pypi.org/simple\n\n"
        + compiled_requirement("httpx", "0.28.1")
        + compiled_requirement("pillow", "1.0")
        + compiled_requirement("pydantic", "2.13.4")
        + compiled_requirement("pyyaml", "6.0.3")
    )

    with pytest.raises(RuntimeError, match="does not satisfy"):
        module._validate_lock_text(
            root,
            "requirements.txt",
            "requirements-runtime.lock",
            text,
            digest,
        )


def test_exact_constraint_uses_pep440_local_version_semantics() -> None:
    module = load_lock_module()

    assert module._version_satisfies("2.7.1+cpu", "==2.7.1") is True
    assert module._version_satisfies("2.7.1+cpu", "==2.7.1+cpu") is True
    assert module._version_satisfies("2.7.1+cuda", "==2.7.1+cpu") is False


def test_exact_constraint_rejects_noncanonical_local_candidate() -> None:
    module = load_lock_module()

    with pytest.raises(RuntimeError, match="unsupported exact dependency version"):
        module._version_satisfies("2.7.1+CPU", "==2.7.1+cpu")


def test_exact_local_pin_remains_supported_by_input_grammar() -> None:
    module = load_lock_module()

    assert (
        module._canonical_input_requirement("Torch==2.7.1+cpu")
        == "torch==2.7.1+cpu"
    )


@pytest.mark.parametrize(
    "requirement",
    [
        'example>=1; python_version >= "3.12"',
        "example @ https://example.invalid/package.whl",
        "example^=1.2",
        "example==1.*",
        "example!=1.2",
        "example~=1.2",
        "example<=1.2",
        "example>=1.4rc1",
        "example>=1.4.post1",
        "example>=1.4+local",
    ],
)
def test_input_requirement_rejects_unsupported_constraint_forms(
    requirement: str,
) -> None:
    module = load_lock_module()

    with pytest.raises(RuntimeError, match="unsupported dependency requirement"):
        module._canonical_input_requirement(requirement)


def test_cli_requires_python_312_isolated_mode() -> None:
    completed = subprocess.run(
        [sys.executable, str(LOCK_SCRIPT), "--check"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert completed.returncode == 1
    assert "Python 3.12" in completed.stderr
    assert "-I" in completed.stderr


@pytest.mark.parametrize(
    ("version_info", "isolated"),
    [((3, 11, 9), 1), ((3, 13, 0), 1), ((3, 12, 0), 0)],
)
def test_interpreter_validation_rejects_wrong_version_or_nonisolated_mode(
    version_info: tuple[int, int, int], isolated: int
) -> None:
    module = load_lock_module()

    with pytest.raises(RuntimeError, match="Python 3.12.*-I"):
        module._validate_interpreter(version_info=version_info, isolated=isolated)
