"""Standard-library parsing and validation for generated dependency locks."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re
import tomllib


BUILD_REQUIREMENTS = "requirements-build.txt"
SOURCE_DIGEST_PREFIX = "# source-sha256: "
AUTOGENERATED_HEADER = "# This file is autogenerated by scripts/lock_dependencies.py.\n"
PYPI_INDEX = "https://pypi.org/simple"
PYTORCH_CPU_INDEX = "https://download.pytorch.org/whl/cpu"
# During a reviewed closure transition, add the new exact profile alongside
# the current one so the authenticated old toolchain can stage its successor.
TRUSTED_BUILD_TOOL_CLOSURES = (
    frozenset(
        {
            "build",
            "click",
            "packaging",
            "pip",
            "pip-tools",
            "pyproject-hooks",
            "setuptools",
            "wheel",
        }
    ),
)
_RELEASE_VERSION = r"(?:0|[1-9][0-9]*)(?:\.(?:0|[1-9][0-9]*))*"
_LOCAL_VERSION = r"[a-z0-9]+(?:\.[a-z0-9]+)*"
_EXACT_VERSION = rf"{_RELEASE_VERSION}(?:\+{_LOCAL_VERSION})?"
_CONSTRAINT_CLAUSE = rf"(?:=={_EXACT_VERSION}|>={_RELEASE_VERSION})"
_INPUT_REQUIREMENT = re.compile(
    rf"([A-Za-z0-9][A-Za-z0-9._-]*)({_CONSTRAINT_CLAUSE})?"
)
_CLAUSE = re.compile(rf"(==|>=)({_EXACT_VERSION})")
_PINNED_REQUIREMENT = re.compile(r"([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\;]+)")
_FINAL_HASH_LINE = re.compile(r" {4}--hash=sha256:[0-9a-f]{64}")
_CONTINUED_HASH_LINE = re.compile(r" {4}--hash=sha256:[0-9a-f]{64} \\")


def normalized_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in text.split("\n")]
    return "\n".join(lines).strip("\n") + "\n"


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def canonical_input_requirement(requirement: str) -> str:
    normalized = re.sub(r"\s+", "", requirement)
    match = _INPUT_REQUIREMENT.fullmatch(normalized)
    if match is None:
        raise RuntimeError(f"unsupported dependency requirement: {requirement!r}")
    name, constraint = match.groups()
    return canonical_name(name) + constraint


def input_requirement_name(requirement: str) -> str:
    normalized = canonical_input_requirement(requirement)
    match = _INPUT_REQUIREMENT.fullmatch(normalized)
    if match is None:  # Defensive: canonicalization already enforces this grammar.
        raise RuntimeError(f"unsupported dependency requirement: {requirement!r}")
    return canonical_name(match.group(1))


def input_requirement_constraints(requirement: str) -> tuple[str, ...]:
    normalized = canonical_input_requirement(requirement)
    match = _INPUT_REQUIREMENT.fullmatch(normalized)
    if match is None:  # Defensive: canonicalization already enforces this grammar.
        raise RuntimeError(f"unsupported dependency requirement: {requirement!r}")
    constraint_text = match.group(2) or ""
    return tuple(filter(None, constraint_text.split(",")))


def _release_tuple(version: str) -> tuple[int, ...]:
    public = version.split("+", 1)[0]
    if re.fullmatch(r"[0-9]+(?:\.[0-9]+)*", public) is None:
        raise RuntimeError(f"unsupported ordered dependency version: {version!r}")
    return tuple(int(component) for component in public.split("."))


def _compare_release(left: tuple[int, ...], right: tuple[int, ...]) -> int:
    width = max(len(left), len(right))
    normalized_left = left + (0,) * (width - len(left))
    normalized_right = right + (0,) * (width - len(right))
    return (normalized_left > normalized_right) - (normalized_left < normalized_right)


def version_satisfies(pinned_version: str, constraint: str) -> bool:
    match = _CLAUSE.fullmatch(constraint)
    if match is None:
        raise RuntimeError(f"unsupported dependency constraint: {constraint!r}")
    operator, expected_version = match.groups()
    if operator == "==":
        if re.fullmatch(_EXACT_VERSION, pinned_version) is None:
            raise RuntimeError(
                f"unsupported exact dependency version: {pinned_version!r}"
            )
        pinned_public, _, pinned_local = pinned_version.partition("+")
        expected_public, _, expected_local = expected_version.partition("+")
        if _compare_release(
            _release_tuple(pinned_public), _release_tuple(expected_public)
        ):
            return False
        return not expected_local or pinned_local == expected_local

    pinned_release = _release_tuple(pinned_version)
    expected_release = _release_tuple(expected_version)
    return _compare_release(pinned_release, expected_release) >= 0


def manifest_requirements(path: Path, allowed_directives: tuple[str, ...]) -> tuple[str, ...]:
    directives: list[str] = []
    requirements: list[str] = []
    for raw_line in normalized_text(path).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-"):
            directives.append(line)
            continue
        requirements.append(canonical_input_requirement(line))
    if tuple(directives) != allowed_directives:
        raise RuntimeError(
            f"dependency input mismatch: {path.name} has unexpected index directives"
        )
    if len(set(requirements)) != len(requirements):
        raise RuntimeError(f"dependency input mismatch: {path.name} has duplicates")
    return tuple(sorted(requirements))


def validate_build_requirements(root: Path) -> tuple[str, ...]:
    requirements = manifest_requirements(root / BUILD_REQUIREMENTS, ())
    names = {input_requirement_name(requirement) for requirement in requirements}
    if "pip-tools" not in names or any("==" not in item for item in requirements):
        raise RuntimeError(
            f"{BUILD_REQUIREMENTS} must exact-pin every tool including pip-tools"
        )
    return requirements


def _project_dependency_metadata(path: Path) -> dict[str, object]:
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    project = document.get("project", {})
    optional = project.get("optional-dependencies", {})
    return {
        "dependencies": project.get("dependencies", []),
        "detector": optional.get("detector", []) if isinstance(optional, dict) else [],
    }


def _project_requirements(values: object, section: str) -> tuple[str, ...]:
    if not isinstance(values, list) or not all(isinstance(value, str) for value in values):
        raise RuntimeError(f"pyproject.toml {section} must be a list of requirements")
    normalized = [canonical_input_requirement(value) for value in values]
    if len(set(normalized)) != len(normalized):
        raise RuntimeError(f"pyproject.toml {section} has duplicate requirements")
    return tuple(sorted(normalized))


def validate_dependency_inputs(root: Path) -> None:
    """Ensure lock inputs and the corresponding project metadata cannot drift."""

    validate_build_requirements(root)
    metadata = _project_dependency_metadata(root / "pyproject.toml")
    comparisons = (
        ("requirements.txt", (), metadata["dependencies"], "project.dependencies"),
        (
            "requirements-detector.txt",
            (f"--extra-index-url {PYTORCH_CPU_INDEX}",),
            metadata["detector"],
            "project.optional-dependencies.detector",
        ),
    )
    for manifest, directives, project_values, section in comparisons:
        actual = manifest_requirements(root / manifest, directives)
        expected = _project_requirements(project_values, section)
        if actual != expected:
            raise RuntimeError(
                f"dependency input mismatch: {manifest} does not match "
                f"pyproject.toml {section}"
            )


def _dependency_metadata(path: Path) -> bytes:
    # Development extras do not feed the runtime or detector locks.
    dependency_sections = _project_dependency_metadata(path)
    return json.dumps(
        dependency_sections,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def compute_source_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in ("requirements.txt", "requirements-detector.txt"):
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(normalized_text(root / relative_path).encode("utf-8"))
        digest.update(b"\0")
    digest.update(b"pyproject.toml:runtime-and-detector-dependencies\0")
    digest.update(_dependency_metadata(root / "pyproject.toml"))
    return digest.hexdigest()


def compute_build_source_digest(root: Path) -> str:
    digest = hashlib.sha256()
    digest.update(b"requirements-build.txt\0")
    digest.update(normalized_text(root / BUILD_REQUIREMENTS).encode("utf-8"))
    return digest.hexdigest()


def digest_for_source(root: Path, source: str) -> str:
    if source == BUILD_REQUIREMENTS:
        return compute_build_source_digest(root)
    return compute_source_digest(root)


def _expected_directives(source: str) -> tuple[str, ...]:
    directives = [f"--index-url {PYPI_INDEX}"]
    if source == "requirements-detector.txt":
        directives.append(f"--extra-index-url {PYTORCH_CPU_INDEX}")
    return tuple(directives)


def _parse_lock_text(
    destination: str,
    text: str,
    expected_directives: tuple[str, ...],
) -> tuple[str, dict[str, str]]:
    lines = text.splitlines()
    expected_header = AUTOGENERATED_HEADER.rstrip("\n")
    if len(lines) < 3 or lines[0] != expected_header:
        raise RuntimeError(f"{destination} has an invalid header")
    digest_match = re.fullmatch(
        re.escape(SOURCE_DIGEST_PREFIX) + r"([0-9a-f]{64})", lines[1]
    )
    if digest_match is None:
        raise RuntimeError(f"{destination} has an invalid source digest")

    directives: list[str] = []
    pinned_versions: dict[str, str] = {}
    index = 2
    while index < len(lines):
        raw_line = lines[index]
        if raw_line.rstrip(" \t") != raw_line:
            raise RuntimeError(f"{destination} has trailing whitespace")
        line = raw_line.strip()
        if not line or line.startswith("#"):
            index += 1
            continue
        if raw_line.startswith((" ", "\t")):
            raise RuntimeError(f"{destination} has an orphan continuation line")
        if line.startswith("--"):
            directives.append(line)
            index += 1
            continue
        if raw_line != line or not line.endswith(" \\"):
            raise RuntimeError(f"{destination} has invalid requirement continuation syntax")
        match = _PINNED_REQUIREMENT.fullmatch(line[:-2])
        if match is None:
            raise RuntimeError(f"{destination} has a requirement without an exact pin")
        package_name = canonical_name(match.group(1))
        if package_name in pinned_versions:
            raise RuntimeError(f"{destination} has a duplicate requirement")
        pinned_versions[package_name] = match.group(2)
        index += 1
        hash_lines: list[str] = []
        while index < len(lines) and lines[index].startswith((" ", "\t")):
            hash_lines.append(lines[index])
            index += 1
        if not hash_lines:
            raise RuntimeError(f"{destination} has a requirement without a SHA-256 hash")
        for hash_index, hash_line in enumerate(hash_lines):
            if hash_line.rstrip(" \t") != hash_line:
                raise RuntimeError(f"{destination} has trailing whitespace")
            pattern = (
                _CONTINUED_HASH_LINE
                if hash_index < len(hash_lines) - 1
                else _FINAL_HASH_LINE
            )
            if pattern.fullmatch(hash_line) is None:
                raise RuntimeError(f"{destination} has invalid hash continuation syntax")

    if tuple(directives) != expected_directives:
        raise RuntimeError(f"{destination} has unexpected index directives")
    return digest_match.group(1), pinned_versions


def detached_build_lock_versions(text: str, destination: str) -> tuple[str, dict[str, str]]:
    digest, versions = _parse_lock_text(
        destination, text, (f"--index-url {PYPI_INDEX}",)
    )
    if frozenset(versions) not in TRUSTED_BUILD_TOOL_CLOSURES:
        raise RuntimeError(f"{destination} does not match a trusted build tool closure")
    return digest, versions


def validate_lock_text(
    root: Path,
    source: str,
    destination: str,
    text: str,
    digest: str,
) -> dict[str, str]:
    actual_digest, pinned_versions = _parse_lock_text(
        destination, text, _expected_directives(source)
    )
    if actual_digest != digest:
        raise RuntimeError(f"stale dependency lock: {destination}")
    direct_requirements = manifest_requirements(
        root / source,
        (f"--extra-index-url {PYTORCH_CPU_INDEX}",)
        if source == "requirements-detector.txt"
        else (),
    )
    direct_names = {input_requirement_name(requirement) for requirement in direct_requirements}
    missing = sorted(direct_names - pinned_versions.keys())
    if missing:
        raise RuntimeError(
            f"{destination} is missing direct dependencies: {', '.join(missing)}"
        )
    for requirement in direct_requirements:
        name = input_requirement_name(requirement)
        pinned_version = pinned_versions[name]
        for constraint in input_requirement_constraints(requirement):
            if not version_satisfies(pinned_version, constraint):
                raise RuntimeError(
                    f"{destination} direct pin {name}=={pinned_version} "
                    f"does not satisfy {constraint}"
                )
    return pinned_versions
