#!/usr/bin/env python3
"""Generate or validate reproducible dependency lock manifests."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import tomllib


COMMANDS = (
    ("requirements.txt", "requirements-runtime.lock"),
    ("requirements-detector.txt", "requirements-detector.lock"),
)
BUILD_REQUIREMENTS = "requirements-build.txt"
SOURCE_DIGEST_PREFIX = "# source-sha256: "
AUTOGENERATED_HEADER = (
    "# This file is autogenerated by scripts/lock_dependencies.py.\n"
)
PYPI_INDEX = "https://pypi.org/simple"
PYTORCH_CPU_INDEX = "https://download.pytorch.org/whl/cpu"


def _normalized_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in text.split("\n")]
    return "\n".join(lines).strip("\n") + "\n"


def _dependency_metadata(path: Path) -> bytes:
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    project = document.get("project", {})
    dependency_sections = {
        "dependencies": project.get("dependencies", []),
        "optional-dependencies": project.get("optional-dependencies", {}),
    }
    return json.dumps(
        dependency_sections,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def compute_source_digest(root: Path) -> str:
    """Hash normalized inputs that can change the resolved dependency sets."""

    digest = hashlib.sha256()
    for relative_path in ("requirements.txt", "requirements-detector.txt"):
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(_normalized_text(root / relative_path).encode("utf-8"))
        digest.update(b"\0")
    digest.update(b"pyproject.toml:dependencies\0")
    digest.update(_dependency_metadata(root / "pyproject.toml"))
    return digest.hexdigest()


def _required_pip_tools_version(root: Path) -> str:
    text = _normalized_text(root / BUILD_REQUIREMENTS)
    match = re.fullmatch(r"pip-tools==([^\s]+)\n", text)
    if match is None:
        raise RuntimeError(
            f"{BUILD_REQUIREMENTS} must contain one exact pip-tools version pin"
        )
    return match.group(1)


def _validate_build_tool(root: Path) -> None:
    expected = _required_pip_tools_version(root)
    try:
        actual = importlib.metadata.version("pip-tools")
    except importlib.metadata.PackageNotFoundError as exc:
        raise RuntimeError(
            f"pip-tools {expected} is required; install {BUILD_REQUIREMENTS} "
            "in an isolated environment"
        ) from exc
    if actual != expected:
        raise RuntimeError(f"pip-tools {expected} is required; found {actual}")


def _read_lock_digest(path: Path) -> str | None:
    try:
        with path.open(encoding="utf-8") as handle:
            for _ in range(8):
                line = handle.readline()
                if not line:
                    break
                if line.startswith(SOURCE_DIGEST_PREFIX):
                    value = line.removeprefix(SOURCE_DIGEST_PREFIX).strip()
                    if re.fullmatch(r"[0-9a-f]{64}", value):
                        return value
                    return None
    except OSError:
        return None
    return None


def check_locks(root: Path) -> int:
    expected = compute_source_digest(root)
    failures: list[str] = []
    for _, destination in COMMANDS:
        path = root / destination
        if not path.is_file():
            failures.append(f"missing dependency lock: {destination}")
            continue
        actual = _read_lock_digest(path)
        if actual != expected:
            failures.append(f"stale dependency lock: {destination}")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "run python3 scripts/lock_dependencies.py in the pinned build environment",
            file=sys.stderr,
        )
        return 1
    print(f"dependency locks are current ({expected})")
    return 0


def normalize_detector_indexes(compiled: str) -> str:
    resolver_directives = (
        f"--index-url {PYTORCH_CPU_INDEX}\n"
        f"--extra-index-url {PYPI_INDEX}\n"
    )
    if not compiled.startswith(resolver_directives):
        raise RuntimeError("pip-tools emitted unexpected detector index directives")
    return compiled.replace(
        resolver_directives,
        f"--extra-index-url {PYTORCH_CPU_INDEX}\n",
        1,
    )


def _compile_lock(root: Path, source: str, destination: str, digest: str) -> None:
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination}.", suffix=".tmp", dir=root
    )
    os.close(file_descriptor)
    temporary = Path(temporary_name)
    try:
        command = [
            sys.executable,
            "-m",
            "piptools",
            "compile",
            "--no-color",
            "--quiet",
            "--generate-hashes",
            "--resolver=backtracking",
            "--strip-extras",
            "--allow-unsafe",
            "--no-reuse-hashes",
            "--no-header",
            "--no-annotate",
            "--newline=lf",
            f"--output-file={temporary.name}",
        ]
        if source == "requirements-detector.txt":
            # pip-tools cannot hash PEP 440 local versions (such as ``+cpu``)
            # when their registry is only an extra index. Resolve with that
            # registry primary, then restore pip's normal PyPI/CPU index order
            # in the portable lock file.
            command.extend(
                [
                    f"--index-url={PYTORCH_CPU_INDEX}",
                    f"--extra-index-url={PYPI_INDEX}",
                ]
            )
        command.append(source)
        subprocess.run(
            command,
            cwd=root,
            check=True,
        )
        generated = temporary.read_text(encoding="utf-8")
        if source == "requirements-detector.txt":
            generated = normalize_detector_indexes(generated)
        header = AUTOGENERATED_HEADER + SOURCE_DIGEST_PREFIX + digest + "\n\n"
        temporary.write_text(header + generated.lstrip("\n"), encoding="utf-8", newline="\n")
        os.replace(temporary, root / destination)
    finally:
        temporary.unlink(missing_ok=True)


def generate_locks(root: Path) -> None:
    _validate_build_tool(root)
    digest = compute_source_digest(root)
    for source, destination in COMMANDS:
        print(f"generating {destination} from {source}")
        _compile_lock(root, source, destination, digest)
    print(f"generated dependency locks ({digest})")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate lock source digests without resolving dependencies",
    )
    arguments = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    if arguments.check:
        return check_locks(root)
    try:
        generate_locks(root)
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"dependency lock generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
