#!/usr/bin/env python3
"""Generate or validate reproducible dependency lock manifests."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import tomllib


COMMANDS = (
    ("requirements.txt", "requirements-runtime.lock"),
    ("requirements-detector.txt", "requirements-detector.lock"),
)
BUILD_REQUIREMENTS = "requirements-build.txt"
SOURCE_DIGEST_PREFIX = "# source-sha256: "
AUTOGENERATED_HEADER = "# This file is autogenerated by scripts/lock_dependencies.py.\n"
PYPI_INDEX = "https://pypi.org/simple"
PYTORCH_CPU_INDEX = "https://download.pytorch.org/whl/cpu"
_INPUT_REQUIREMENT = re.compile(
    r"([A-Za-z0-9][A-Za-z0-9._-]*)"
    r"((?:(?:===|~=|==|!=|<=|>=|<|>)[^,;\s]+)"
    r"(?:,(?:===|~=|==|!=|<=|>=|<|>)[^,;\s]+)*)?"
)
_PINNED_REQUIREMENT = re.compile(r"([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\;]+)")
_HASH_LINE = re.compile(r"--hash=sha256:[0-9a-f]{64}")


def _normalized_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in text.split("\n")]
    return "\n".join(lines).strip("\n") + "\n"


def _canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _canonical_input_requirement(requirement: str) -> str:
    normalized = re.sub(r"\s+", "", requirement)
    match = _INPUT_REQUIREMENT.fullmatch(normalized)
    if match is None:
        raise RuntimeError(f"unsupported dependency requirement: {requirement!r}")
    name, constraint = match.groups()
    return _canonical_name(name) + constraint


def _input_requirement_name(requirement: str) -> str:
    normalized = _canonical_input_requirement(requirement)
    match = _INPUT_REQUIREMENT.fullmatch(normalized)
    if match is None:  # Defensive: canonicalization already enforces this grammar.
        raise RuntimeError(f"unsupported dependency requirement: {requirement!r}")
    return _canonical_name(match.group(1))


def _manifest_requirements(path: Path, allowed_directives: tuple[str, ...]) -> tuple[str, ...]:
    directives: list[str] = []
    requirements: list[str] = []
    for raw_line in _normalized_text(path).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-"):
            directives.append(line)
            continue
        requirements.append(_canonical_input_requirement(line))
    if tuple(directives) != allowed_directives:
        raise RuntimeError(
            f"dependency input mismatch: {path.name} has unexpected index directives"
        )
    if len(set(requirements)) != len(requirements):
        raise RuntimeError(f"dependency input mismatch: {path.name} has duplicates")
    return tuple(sorted(requirements))


def _project_dependency_metadata(path: Path) -> dict[str, object]:
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    project = document.get("project", {})
    optional = project.get("optional-dependencies", {})
    return {
        "dependencies": project.get("dependencies", []),
        "detector": optional.get("detector", []) if isinstance(optional, dict) else [],
    }


def _project_requirements(values: object, section: str) -> tuple[str, ...]:
    if not isinstance(values, list) or not all(isinstance(value, str) for value in values):
        raise RuntimeError(f"pyproject.toml {section} must be a list of requirements")
    normalized = [_canonical_input_requirement(value) for value in values]
    if len(set(normalized)) != len(normalized):
        raise RuntimeError(f"pyproject.toml {section} has duplicate requirements")
    return tuple(sorted(normalized))


def validate_dependency_inputs(root: Path) -> None:
    """Ensure lock inputs and the corresponding project metadata cannot drift."""

    metadata = _project_dependency_metadata(root / "pyproject.toml")
    comparisons = (
        (
            "requirements.txt",
            (),
            metadata["dependencies"],
            "project.dependencies",
        ),
        (
            "requirements-detector.txt",
            (f"--extra-index-url {PYTORCH_CPU_INDEX}",),
            metadata["detector"],
            "project.optional-dependencies.detector",
        ),
    )
    for manifest, directives, project_values, section in comparisons:
        actual = _manifest_requirements(root / manifest, directives)
        expected = _project_requirements(project_values, section)
        if actual != expected:
            raise RuntimeError(
                f"dependency input mismatch: {manifest} does not match "
                f"pyproject.toml {section}"
            )


def _dependency_metadata(path: Path) -> bytes:
    # Only runtime and detector metadata feed these two locks. Development
    # extras are intentionally independent and do not invalidate them.
    dependency_sections = _project_dependency_metadata(path)
    return json.dumps(
        dependency_sections,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def compute_source_digest(root: Path) -> str:
    """Hash normalized inputs that can change the resolved dependency sets."""

    digest = hashlib.sha256()
    for relative_path in ("requirements.txt", "requirements-detector.txt"):
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(_normalized_text(root / relative_path).encode("utf-8"))
        digest.update(b"\0")
    digest.update(b"pyproject.toml:runtime-and-detector-dependencies\0")
    digest.update(_dependency_metadata(root / "pyproject.toml"))
    return digest.hexdigest()


def _required_build_tool_versions(root: Path) -> dict[str, str]:
    versions: dict[str, str] = {}
    for line in _normalized_text(root / BUILD_REQUIREMENTS).splitlines():
        if not line or line.startswith("#"):
            continue
        match = re.fullmatch(r"([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s]+)", line)
        if match is None:
            raise RuntimeError(
                f"{BUILD_REQUIREMENTS} must contain only exact tool version pins"
            )
        name, version = match.groups()
        canonical = _canonical_name(name)
        if canonical in versions:
            raise RuntimeError(f"{BUILD_REQUIREMENTS} contains duplicate pin {name}")
        versions[canonical] = version
    if "pip-tools" not in versions:
        raise RuntimeError(f"{BUILD_REQUIREMENTS} must pin pip-tools")
    return versions


def _validate_build_tool(root: Path) -> None:
    for name, expected in _required_build_tool_versions(root).items():
        try:
            actual = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError as exc:
            raise RuntimeError(
                f"{name} {expected} is required; recreate the isolated build environment"
            ) from exc
        if actual != expected:
            raise RuntimeError(f"{name} {expected} is required; found {actual}")


def _expected_directives(source: str) -> tuple[str, ...]:
    directives = [f"--index-url {PYPI_INDEX}"]
    if source == "requirements-detector.txt":
        directives.append(f"--extra-index-url {PYTORCH_CPU_INDEX}")
    return tuple(directives)


def _validate_lock_text(
    root: Path,
    source: str,
    destination: str,
    text: str,
    digest: str,
) -> None:
    lines = text.splitlines()
    expected_header = AUTOGENERATED_HEADER.rstrip("\n")
    expected_digest = SOURCE_DIGEST_PREFIX + digest
    if len(lines) < 3 or lines[0] != expected_header:
        raise RuntimeError(f"{destination} has an invalid header")
    if lines[1] != expected_digest:
        raise RuntimeError(f"stale dependency lock: {destination}")

    directives: list[str] = []
    pinned_names: set[str] = set()
    index = 2
    while index < len(lines):
        raw_line = lines[index]
        line = raw_line.strip()
        if not line or line.startswith("#"):
            index += 1
            continue
        if raw_line.startswith((" ", "\t")):
            raise RuntimeError(f"{destination} has an orphan continuation line")
        if line.startswith("--"):
            directives.append(line)
            index += 1
            continue
        if not line.endswith("\\"):
            raise RuntimeError(f"{destination} has invalid requirement continuation syntax")
        match = _PINNED_REQUIREMENT.fullmatch(line[:-1].rstrip())
        if match is None:
            raise RuntimeError(f"{destination} has a requirement without an exact pin")
        package_name = _canonical_name(match.group(1))
        if package_name in pinned_names:
            raise RuntimeError(f"{destination} has a duplicate requirement")
        pinned_names.add(package_name)
        index += 1
        hash_lines: list[str] = []
        while index < len(lines) and lines[index].startswith((" ", "\t")):
            hash_lines.append(lines[index].strip())
            index += 1
        if not hash_lines:
            raise RuntimeError(f"{destination} has a requirement without a SHA-256 hash")
        for hash_index, hash_line in enumerate(hash_lines):
            continues = hash_line.endswith("\\")
            value = hash_line[:-1].rstrip() if continues else hash_line
            if _HASH_LINE.fullmatch(value) is None:
                raise RuntimeError(f"{destination} has an invalid requirement continuation")
            if continues != (hash_index < len(hash_lines) - 1):
                raise RuntimeError(f"{destination} has invalid hash continuation syntax")

    if tuple(directives) != _expected_directives(source):
        raise RuntimeError(f"{destination} has unexpected index directives")
    direct_names = {
        _input_requirement_name(requirement)
        for requirement in _manifest_requirements(
            root / source,
            (f"--extra-index-url {PYTORCH_CPU_INDEX}",)
            if source == "requirements-detector.txt"
            else (),
        )
    }
    missing = sorted(direct_names - pinned_names)
    if missing:
        raise RuntimeError(
            f"{destination} is missing direct dependencies: {', '.join(missing)}"
        )


def check_locks(root: Path) -> int:
    failures: list[str] = []
    try:
        validate_dependency_inputs(root)
        expected = compute_source_digest(root)
    except (OSError, RuntimeError, tomllib.TOMLDecodeError) as exc:
        failures.append(str(exc))
        expected = ""
    if expected:
        for source, destination in COMMANDS:
            path = root / destination
            if not path.is_file():
                failures.append(f"missing dependency lock: {destination}")
                continue
            try:
                text = path.read_text(encoding="utf-8")
                _validate_lock_text(root, source, destination, text, expected)
            except (OSError, RuntimeError, UnicodeError) as exc:
                failures.append(f"invalid dependency lock: {destination}: {exc}")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "run python3 scripts/lock_dependencies.py in a recreated pinned build environment",
            file=sys.stderr,
        )
        return 1
    print(f"dependency locks are current ({expected})")
    return 0


def normalize_detector_indexes(compiled: str) -> str:
    resolver_directives = (
        f"--index-url {PYTORCH_CPU_INDEX}\n"
        f"--extra-index-url {PYPI_INDEX}\n"
    )
    if not compiled.startswith(resolver_directives):
        raise RuntimeError("pip-tools emitted unexpected detector index directives")
    installed_directives = (
        f"--index-url {PYPI_INDEX}\n"
        f"--extra-index-url {PYTORCH_CPU_INDEX}\n"
    )
    return compiled.replace(resolver_directives, installed_directives, 1)


def _resolver_environment() -> dict[str, str]:
    environment = {
        name: value
        for name, value in os.environ.items()
        if not name.startswith("PIP_") and name not in {"PYTHONHOME", "PYTHONPATH"}
    }
    environment["PIP_CONFIG_FILE"] = os.devnull
    environment["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
    environment["PYTHONSAFEPATH"] = "1"
    return environment


def _compile_lock(root: Path, source: str, destination: str, digest: str) -> Path:
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination}.", suffix=".tmp", dir=root
    )
    os.close(file_descriptor)
    temporary = Path(temporary_name)
    try:
        command = [
            sys.executable,
            "-P",
            "-m",
            "piptools",
            "compile",
            "--no-color",
            "--quiet",
            "--generate-hashes",
            "--resolver=backtracking",
            "--strip-extras",
            "--allow-unsafe",
            "--no-reuse-hashes",
            "--no-header",
            "--no-annotate",
            "--newline=lf",
            f"--output-file={temporary.name}",
        ]
        if source == "requirements-detector.txt":
            # pip-tools cannot hash PEP 440 local versions (such as ``+cpu``)
            # when their registry is only an extra index. Resolve with that
            # registry primary, then restore the reviewed install order.
            command.extend(
                [
                    f"--index-url={PYTORCH_CPU_INDEX}",
                    f"--extra-index-url={PYPI_INDEX}",
                ]
            )
        else:
            command.append(f"--index-url={PYPI_INDEX}")
        command.append(source)
        subprocess.run(
            command,
            cwd=root,
            check=True,
            env=_resolver_environment(),
        )
        generated = temporary.read_text(encoding="utf-8")
        if source == "requirements-detector.txt":
            generated = normalize_detector_indexes(generated)
        else:
            generated = f"--index-url {PYPI_INDEX}\n\n" + generated.lstrip("\n")
        header = AUTOGENERATED_HEADER + SOURCE_DIGEST_PREFIX + digest + "\n\n"
        final_text = header + generated.lstrip("\n")
        try:
            _validate_lock_text(root, source, destination, final_text, digest)
        except RuntimeError as exc:
            raise RuntimeError(f"invalid generated dependency lock: {exc}") from exc
        temporary.write_text(final_text, encoding="utf-8", newline="\n")
        temporary.chmod(0o644)
        return temporary
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def generate_locks(root: Path) -> None:
    _validate_build_tool(root)
    validate_dependency_inputs(root)
    digest = compute_source_digest(root)
    staged: list[tuple[Path, Path]] = []
    try:
        for source, destination in COMMANDS:
            print(f"generating {destination} from {source}")
            temporary = _compile_lock(root, source, destination, digest)
            staged.append((temporary, root / destination))
        for temporary, destination in staged:
            os.replace(temporary, destination)
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)
    print(f"generated dependency locks ({digest})")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate lock inputs, contents, and source digests without resolving",
    )
    arguments = parser.parse_args(argv)
    try:
        if arguments.check:
            return check_locks(Path(__file__).resolve().parents[1])
        generate_locks(Path(__file__).resolve().parents[1])
    except (OSError, RuntimeError, subprocess.CalledProcessError, tomllib.TOMLDecodeError) as exc:
        print(f"dependency lock generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
