#!/usr/bin/env python3
"""Generate or validate reproducible dependency lock manifests."""

from __future__ import annotations

import argparse
import importlib.metadata
import importlib.util
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import tomllib
from types import ModuleType


def _load_validation_support() -> ModuleType:
    path = Path(__file__).resolve().with_name("dependency_lock_validation.py")
    spec = importlib.util.spec_from_file_location("_dependency_lock_validation", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("dependency lock validation support is unavailable")
    module = importlib.util.module_from_spec(spec)
    previous_bytecode_setting = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = previous_bytecode_setting
    return module


_validation = _load_validation_support()
BUILD_REQUIREMENTS = _validation.BUILD_REQUIREMENTS
SOURCE_DIGEST_PREFIX = _validation.SOURCE_DIGEST_PREFIX
AUTOGENERATED_HEADER = _validation.AUTOGENERATED_HEADER
PYPI_INDEX = _validation.PYPI_INDEX
PYTORCH_CPU_INDEX = _validation.PYTORCH_CPU_INDEX
_validate_build_requirements = _validation.validate_build_requirements
_canonical_name = _validation.canonical_name
_canonical_input_requirement = _validation.canonical_input_requirement
_input_requirement_name = _validation.input_requirement_name
_version_satisfies = _validation.version_satisfies
validate_dependency_inputs = _validation.validate_dependency_inputs
compute_source_digest = _validation.compute_source_digest
compute_build_source_digest = _validation.compute_build_source_digest
_digest_for_source = _validation.digest_for_source
_validate_lock_text = _validation.validate_lock_text
_detached_build_lock_versions = _validation.detached_build_lock_versions

NEXT_BUILD_LOCK = "requirements-build.next.lock"
COMMANDS = (
    ("requirements-build.txt", "requirements-build.lock"),
    ("requirements.txt", "requirements-runtime.lock"),
    ("requirements-detector.txt", "requirements-detector.lock"),
)


def _validate_installed_versions(expected_versions: dict[str, str]) -> None:
    for name, expected in expected_versions.items():
        try:
            actual = importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError as exc:
            raise RuntimeError(
                f"{name} {expected} is required; recreate the isolated build environment"
            ) from exc
        if actual != expected:
            raise RuntimeError(f"{name} {expected} is required; found {actual}")


def _validate_build_tool(root: Path) -> bytes | None:
    current_path = root / "requirements-build.lock"
    current_text = current_path.read_text(encoding="utf-8")
    current_digest, _ = _detached_build_lock_versions(current_text, current_path.name)
    expected_digest = compute_build_source_digest(root)
    next_path = root / NEXT_BUILD_LOCK
    expected_next: bytes | None = None
    if next_path.is_file():
        expected_next = next_path.read_bytes()
        versions = _validate_lock_text(
            root,
            BUILD_REQUIREMENTS,
            NEXT_BUILD_LOCK,
            expected_next.decode("utf-8"),
            expected_digest,
        )
    elif current_digest == expected_digest:
        versions = _validate_lock_text(
            root,
            BUILD_REQUIREMENTS,
            current_path.name,
            current_text,
            expected_digest,
        )
    else:
        raise RuntimeError(
            "build tool input changed; stage an authenticated next build lock first"
        )
    _validate_installed_versions(versions)
    return expected_next


def _validate_interpreter(
    *,
    version_info: tuple[int, ...] | None = None,
    isolated: int | None = None,
) -> None:
    actual_version = tuple(sys.version_info if version_info is None else version_info)
    actual_isolated = sys.flags.isolated if isolated is None else isolated
    if actual_version[:2] != (3, 12) or actual_isolated != 1:
        raise RuntimeError(
            "dependency lock commands require Python 3.12 isolated mode; "
            "invoke this script with python -I"
        )


def check_locks(root: Path) -> int:
    failures: list[str] = []
    try:
        validate_dependency_inputs(root)
    except (OSError, RuntimeError, tomllib.TOMLDecodeError) as exc:
        failures.append(str(exc))
    if not failures:
        for source, destination in COMMANDS:
            path = root / destination
            if not path.is_file():
                failures.append(f"missing dependency lock: {destination}")
                continue
            try:
                expected = _digest_for_source(root, source)
                text = path.read_text(encoding="utf-8")
                _validate_lock_text(root, source, destination, text, expected)
            except (OSError, RuntimeError, UnicodeError) as exc:
                failures.append(f"invalid dependency lock: {destination}: {exc}")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        print(
            "run python3 -I scripts/lock_dependencies.py in a recreated "
            "pinned build environment",
            file=sys.stderr,
        )
        return 1
    print(f"dependency locks are current ({compute_source_digest(root)})")
    return 0


def normalize_detector_indexes(compiled: str) -> str:
    resolver_directives = (
        f"--index-url {PYTORCH_CPU_INDEX}\n"
        f"--extra-index-url {PYPI_INDEX}\n"
    )
    if not compiled.startswith(resolver_directives):
        raise RuntimeError("pip-tools emitted unexpected detector index directives")
    installed_directives = (
        f"--index-url {PYPI_INDEX}\n"
        f"--extra-index-url {PYTORCH_CPU_INDEX}\n"
    )
    return compiled.replace(resolver_directives, installed_directives, 1)


def _resolver_environment() -> dict[str, str]:
    environment = {
        name: value
        for name, value in os.environ.items()
        if not name.startswith("PIP_")
        and name not in {"PYTHONHOME", "PYTHONPATH", "PYTHONUSERBASE"}
    }
    environment["PIP_CONFIG_FILE"] = os.devnull
    environment["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
    environment["PYTHONSAFEPATH"] = "1"
    environment["PYTHONNOUSERSITE"] = "1"
    return environment


def _report_secondary_error(primary: BaseException, label: str, error: OSError) -> None:
    message = f"{label}: {type(error).__name__}: {error}"
    primary.add_note(message)
    print(f"dependency lock cleanup warning: {message}", file=sys.stderr)


def _cleanup_path(path: Path, primary: BaseException) -> None:
    try:
        path.unlink(missing_ok=True)
    except OSError as error:
        _report_secondary_error(primary, "temporary-file cleanup failed", error)


def _snapshot_destination(path: Path) -> tuple[str, bytes | str | None, int | None]:
    if path.is_symlink():
        return ("symlink", os.readlink(path), None)
    if not path.exists():
        return ("absent", None, None)
    if not path.is_file():
        raise RuntimeError(f"dependency lock destination is not a file: {path.name}")
    return ("file", path.read_bytes(), path.stat().st_mode & 0o777)


def _restore_destination(
    path: Path,
    snapshot: tuple[str, bytes | str | None, int | None],
) -> None:
    kind, payload, mode = snapshot
    if kind == "absent":
        path.unlink(missing_ok=True)
        return
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.rollback.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    failure: BaseException | None = None
    try:
        if kind == "symlink":
            os.close(file_descriptor)
            temporary.unlink()
            if not isinstance(payload, str):
                raise RuntimeError("invalid dependency lock symlink snapshot")
            os.symlink(payload, temporary)
        else:
            if not isinstance(payload, bytes) or mode is None:
                raise RuntimeError("invalid dependency lock file snapshot")
            with os.fdopen(file_descriptor, "wb") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            temporary.chmod(mode)
        os.replace(temporary, path)
    except BaseException as primary:
        failure = primary
        raise
    finally:
        if failure is None:
            temporary.unlink(missing_ok=True)
        else:
            _cleanup_path(temporary, failure)


def _compile_lock(root: Path, source: str, destination: str, digest: str) -> Path:
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination}.", suffix=".tmp", dir=root
    )
    os.close(file_descriptor)
    temporary = Path(temporary_name)
    try:
        command = [
            sys.executable,
            "-I",
            "-m",
            "piptools",
            "compile",
            "--no-color",
            "--quiet",
            "--generate-hashes",
            "--resolver=backtracking",
            "--strip-extras",
            "--allow-unsafe",
            "--no-reuse-hashes",
            "--no-header",
            "--no-annotate",
            "--newline=lf",
            f"--output-file={temporary.name}",
        ]
        if source == "requirements-detector.txt":
            # Resolve local CPU versions from their registry as primary, then
            # restore the reviewed PyPI-primary install order.
            command.extend(
                [
                    f"--index-url={PYTORCH_CPU_INDEX}",
                    f"--extra-index-url={PYPI_INDEX}",
                ]
            )
        else:
            command.append(f"--index-url={PYPI_INDEX}")
        command.append(source)
        subprocess.run(
            command,
            cwd=root,
            check=True,
            env=_resolver_environment(),
        )
        generated = temporary.read_text(encoding="utf-8")
        if source == "requirements-detector.txt":
            generated = normalize_detector_indexes(generated)
        else:
            generated = f"--index-url {PYPI_INDEX}\n\n" + generated.lstrip("\n")
        header = AUTOGENERATED_HEADER + SOURCE_DIGEST_PREFIX + digest + "\n\n"
        final_text = header + generated.lstrip("\n")
        try:
            _validate_lock_text(root, source, destination, final_text, digest)
        except RuntimeError as exc:
            raise RuntimeError(f"invalid generated dependency lock: {exc}") from exc
        temporary.write_text(final_text, encoding="utf-8", newline="\n")
        temporary.chmod(0o644)
        return temporary
    except BaseException as primary:
        _cleanup_path(temporary, primary)
        raise


def stage_build_lock(root: Path) -> None:
    current_path = root / "requirements-build.lock"
    _, versions = _detached_build_lock_versions(
        current_path.read_text(encoding="utf-8"), current_path.name
    )
    _validate_installed_versions(versions)
    _validate_build_requirements(root)
    digest = compute_build_source_digest(root)
    temporary = _compile_lock(root, BUILD_REQUIREMENTS, NEXT_BUILD_LOCK, digest)
    try:
        os.replace(temporary, root / NEXT_BUILD_LOCK)
    except BaseException as primary:
        _cleanup_path(temporary, primary)
        raise
    print(f"staged authenticated build lock ({digest})")


def _publish_staged(staged: list[tuple[Path, Path]]) -> None:
    snapshots = {
        destination: _snapshot_destination(destination) for _, destination in staged
    }
    published: list[Path] = []
    try:
        for temporary, destination in staged:
            os.replace(temporary, destination)
            published.append(destination)
    except BaseException as primary:
        for destination in reversed(published):
            try:
                _restore_destination(destination, snapshots[destination])
            except (OSError, RuntimeError) as rollback_error:
                if isinstance(rollback_error, OSError):
                    _report_secondary_error(
                        primary,
                        f"rollback failed for {destination.name}",
                        rollback_error,
                    )
                else:
                    primary.add_note(str(rollback_error))
        raise


def generate_locks(root: Path) -> None:
    expected_build_lock = _validate_build_tool(root)
    validate_dependency_inputs(root)
    staged: list[tuple[Path, Path]] = []
    failure: BaseException | None = None
    try:
        for source, destination in COMMANDS:
            print(f"generating {destination} from {source}")
            digest = _digest_for_source(root, source)
            temporary = _compile_lock(root, source, destination, digest)
            staged.append((temporary, root / destination))
        if expected_build_lock is not None and staged[0][0].read_bytes() != expected_build_lock:
            raise RuntimeError("regenerated build lock differs from authenticated next build lock")
        _publish_staged(staged)
    except BaseException as primary:
        failure = primary
        raise
    finally:
        for temporary, _ in staged:
            if failure is None:
                temporary.unlink(missing_ok=True)
            else:
                _cleanup_path(temporary, failure)
    (root / NEXT_BUILD_LOCK).unlink(missing_ok=True)
    print(f"generated dependency locks ({compute_source_digest(root)})")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="validate lock inputs, contents, and source digests without resolving",
    )
    mode.add_argument(
        "--stage-build-lock",
        action="store_true",
        help="stage a next build lock using the currently authenticated toolchain",
    )
    arguments = parser.parse_args(argv)
    try:
        _validate_interpreter()
        root = Path(__file__).resolve().parents[1]
        if arguments.stage_build_lock:
            stage_build_lock(root)
            return 0
        if arguments.check:
            return check_locks(root)
        generate_locks(root)
    except (OSError, RuntimeError, subprocess.CalledProcessError, tomllib.TOMLDecodeError) as exc:
        print(f"dependency lock generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
